### ISSUE TITLE
Implement lib_count()

### ISSUE THREAD

**Issue by aaronquinton** [UBC-MDS/LibRely-Py-#13]
Complete function code for the lib_count() python function and insure they pass the tests.

**Comment by ehhope** [comment]
The code is coming along great, just having some issues with getting it to run in terminal. I think we may need argparse and will get back to both of you about this concern.

**Comment by aaronquinton** [comment]
Thank you Alex! I reviewed your pull request. I had made the following changes:
- There was a merge conflict with how the function arguments had been defined. The master has defined the input argument as `filepath`, where your branch defined it as `inputfile`. I resolved this conflict.
- We are having issues with argparse playing nice with pytest. For the time being i have commented this out of your code. We can review this later in the project. With this change all the tests have passed.

This issue has been resolved.

**Comment by ehhope** [comment]
Thanks for this correction Aaron!
